myApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Myindex.as_view(), name='home'),
    path('rooms/<int:id>', views.rooms, name = 'rooms'),
    path('create_room',views.create_room,name = "create_room"),
    path('update_room/<int:pk>/',views.update_room,name = 'update_room'),
    path('delete_room/<int:pk>',views.delete_room,name = 'delete_room'),
    path('delete_message/<int:pk>/<int:room_id>/',views.delete_message, name = 'delete_message'),
    path("user_profile/<int:id>",views.user_profile,name = 'profile'),
    path('register/',views.register_view,name = 'register'),
    path('login/',views.login_view,name = 'login'),
    path('logout/',views.MyLogoutView.as_view(), name = 'logout'),
]

myProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myApp.urls'))
]

myApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    name = models.CharField(max_length = 200)

    def __str__(self):
        return self.name[:50]


class Room(models.Model):
    host = models.ForeignKey(User, on_delete = models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete = models.SET_NULL, null = True, related_name = "topic_room_set")
    name = models.CharField(max_length = 30)
    description = models.TextField(null = True, blank = True)
    participants = models.ManyToManyField(User, related_name = "particpiants", blank = True)
    updated = models.DateTimeField(auto_now = True)
    created = models.DateTimeField(auto_now_add = True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.name

class Message(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    room = models.ForeignKey(Room, on_delete = models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now = True)
    created = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.body[:50]

templates/activity.html
<div class="activities">
  <div class="activities__header">
    <h2>Recent Activities</h2>
  </div>

  {% for i in recent_messages %}
  <div class="activities__box">
    <div class="activities__boxHeader roomListRoom__header">
      <a href="{% url 'profile' i.user.id %}" class="roomListRoom__author">
        <div class="avatar avatar--small">
          <img src="https://randomuser.me/api/portraits/women/11.jpg" />
        </div>
        <p>
          @{{ i.user.username }}
          <span>{{ i.created|timesince }} ago</span>
        </p>
      </a>
      <div class="roomListRoom__actions">
        <a href="#">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>remove</title>
            <path
              d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
            ></path>
          </svg>
        </a>
      </div>
    </div>
    <div class="activities__boxContent">
      <p>replied to post “<a href="{% url 'rooms' i.room.id %}">{{ i.room.name }}</a>”</p>
      <div class="activities__boxRoomContent">
        {{ i.body|truncatechars:20 }}
      </div>
    </div>
  </div>
  {% endfor %}

</div>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>
    <title>StudyBuddy - Find study partners around the world!</title>
</head>
<body>
    
    {% include 'header.html' %}
    
    {% if messages %}
    
    <!-- <ul class="messages">
        {% for message in messages %}
        
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        
        {% endfor %}
    </ul> -->
    
    {% endif %}
    
    {% block content %}
    
    {% endblock %}
</body>
</html>

templates/delete_message.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main class="delete-item layout">
    <div class="container">
        <div class="layout__box">
            <div class="layout__boxHeader">
                <div class="layout__boxTitle">
                    <a href="{{ request.META.HTTP_REFERER }}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                            viewBox="0 0 32 32">
                            <title>arrow-left</title>
                            <path
                                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                            </path>
                        </svg>
                    </a>
                    <h3>Back</h3>
                </div>
            </div>
            <div class="layout__body">
                <form class="form" method="POST" action="">
                    {% csrf_token %}
                    <div class="form__group">
                        <p>Are you sure you want to delete your message?</p>
                    </div>

                    <div class="for__group">
                        <input class="btn btn--main" type="submit" value="Confirm" />
                    </div>

                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

templates/delete_room.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main class="delete-item layout">
    <div class="container">
        <div class="layout__box">
            <div class="layout__boxHeader">
                <div class="layout__boxTitle">
                    <a href="{% url 'rooms' obj.id %}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                            viewBox="0 0 32 32">
                            <title>arrow-left</title>
                            <path
                                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                            </path>
                        </svg>
                    </a>
                    <h3>Back</h3>
                </div>
            </div>
            <div class="layout__body">
                <form class="form" method="POST" action="">
                    {% csrf_token %}
                    <div class="form__group">
                        <p>Are you sure you want to delete "{{ obj.name }}"?</p>
                    </div>

                    <div class="for__group">
                        <input class="btn btn--main" type="submit" value="Confirm" />
                    </div>

                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

templates/edit-user.html
{% extends 'base.html' %}
{% load.html %}

{% block content %}
<main class="update-account layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="profile.html">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Edit your profile</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" action="#">
                        <div class="form__group">
                            <label for="profile_pic">Avatar</label>
                            <input id="profile_pic" name="profile_pic" type="file" />
                        </div>

              <div class="form__group">
                <label for="username">Username</label>
                <input id="username" name="username" type="text" placeholder="E.g. John doe" />
              </div>

              <div class="form__group">
                <label for="email">Email</label>
                <input id="email" name="email" type="text" placeholder="E.g. john@email.com" />
              </div>

                        <div class="form__group">
                            <label for="user_bio">Bio</label>
                            <textarea name="user_bio" id="user_bio" placeholder="Write about yourself..."></textarea>
                        </div>
                        <div class="form__action">
                            <a class="btn btn--dark" href="index.html">Cancel</a>
                            <button class="btn btn--main" type="submit">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
      </div>
    </main>
{% endblock content %}

templates/header.html
<header class="header header--loggedIn">
    <div class="container">
        <a href="/" class="header__logo">
            <img src="assets/logo.svg" />
            <h1>StudyBuddy</h1>
        </a>
        <form class="header__search" method="GET" action="{% url 'home' %}">
            <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                    <title>search</title>
                    <path d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"></path>
                </svg>
                <input placeholder="Search for posts" type="search" name="q" />
            </label>
        </form>
        <nav class="header__menu">
            {% if request.user.is_authenticated %}
                <a href="{% url 'profile' request.user.id %}">
                    <div class="avatar avatar--medium active">
                    <img src="https://randomuser.me/api/portraits/men/37.jpg" />
                    </div>
                    <p>{{ request.user.name }} <span>@{{ request.user.username }}</span></p>
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                    <title>chevron-down</title>
                    <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
                    </svg>
                </a>

                <a href="{% url 'logout' %}">
                    Logout
                </a>
            
            {% else %}
                <a href="{% url 'login' %}">
                    <p>Login</p>
                </a>
                <a href="{% url 'register' %}">
                    <p>Register</p>
                </a>
            {% endif %}
        </nav>
    </div>
</header>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main class="layout layout--3">
  <div class="container">
    <!-- Topics Start -->
    {% include 'topics.html' %}
    <!-- Topics End -->

    <!-- Room List Start -->
    {% include 'room_list.html' %}
    <!-- Room List End -->

    <!-- Activities Start -->
    {% include 'activity.html' %}
    <!-- Activities End -->
  </div>
</main>
{% endblock content %}

templates/login_register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main class="auth layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <h3>Login</h3>
        </div>
      </div>
      <div class="layout__body">
        <h2 class="auth__tagline">Find your study partner</h2>

        {% if page == 'login' %}
          <form class="form" method="POST">
            {% csrf_token %}
            <div class="form__group form__group">
              <label for="room_name">Username</label>
              <input id="username" name="username" type="text" placeholder="e.g. dennis_ivy" />
            </div>
            <div class="form__group">
              <label for="password">Password</label>
              <input
                id="password"
                name="password"
                type="password"
                placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"
              />
            </div>

            <button class="btn btn--main" type="submit">
              <svg
                version="1.1"
                xmlns="http://www.w3.org/2000/svg"
                width="32"
                height="32"
                viewBox="0 0 32 32"
              >
                <title>lock</title>
                <path
                  d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
                ></path>
                <path
                  d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
                ></path>
              </svg>

              Login
            </button>
          </form>

          <div class="auth__action">
            <p>Haven't signed up yet?</p>
            <a href="{% url 'register' %}" class="btn btn--link">Sign Up</a>
          </div>
        {% else %}
        <form class="form" method="POST">
          {% csrf_token %}
          <!-- <div class="form__group form__group">
            <label for="fullname">Full Name</label>
            <input id="fullname" name="fullname" type="text" placeholder="e.g. Dennis Ivy" />
          </div>
          <div class="form__group form__group">
            <label for="room_name">Username</label>
            <input id="username" name="username" type="text" placeholder="e.g. dennis_ivy" />
          </div>
          <div class="form__group">
            <label for="password">Password</label>
            <input
              id="password"
              name="password"
              type="password"
              placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"
            />
          </div>

          <div class="form__group">

            <label for="confirm_password">Confirm Password</label>
            <input
              id="confirm_password"
              name="confirm_password"
              type="password"
              placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"
            />
          </div> -->

          {{ form }}

          <button class="btn btn--main" type="submit">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>lock</title>
              <path
                d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
              ></path>
              <path
                d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
              ></path>
            </svg>

            Sign Up
          </button>
        </form>

        <div class="auth__action">
          <p>Already have an account?</p>
          <a href="{% url 'login' %}" class="btn btn--link">Log In</a>
        </div>
        {% endif %}

      </div>
    </div>
  </div>
</main>
{% endblock %}

templates/room_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main class="create-room layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'home' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>
          <h3>{{ action }} Study Room</h3>
        </div>
      </div>
      <div class="layout__body">
        <form class="form" method="POST" action="">
          {% csrf_token %}
          <div class="form__group">
            <label for="room_name">Room Name</label>
            {{ form.name }}
            <!-- <input id="room_name" name="room_name" type="text" placeholder="E.g. Mastering Python + Django" /> -->
          </div>

          <div class="form__group">
            <label for="room_topic">{{ form.topic.label }}</label>
            {{ form.topic }}
          </div>


          <div class="form__group">
            <label for="room_about">About</label>
            {{ form.description }}
            <!-- <textarea name="room_about" id="room_about" placeholder="Write about your study group..."></textarea> -->
          </div>
          <div class="form__action">
            <a class="btn btn--dark" href="{{request.META.HTTP_REFERER}}">Cancel</a>
            <button class="btn btn--main" type="submit">{{ action }} Room</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock %}

templates/room_list.html
{% load static %}

{% block content %}
  <div class="roomList">
    <div class="mobile-menu">
      <form class="header__search">
        <label>
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>search</title>
            <path
              d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
            ></path>
          </svg>
          <input placeholder="Search for posts" />
        </label>
      </form>
      <div class="mobile-menuItems">
        <a class="btn btn--main btn--pill" href="#">Browse Topics</a>
        <a class="btn btn--main btn--pill" href="#">Recent Activities</a>
      </div>
    </div>
    <div class="roomList__header">
      <div>
        <h2>Study Room</h2>
        <p>{{ room_count }} Rooms available</p>
      </div>
      <a class="btn btn--main" href="{% url 'create_room' %}">
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
          <title>add</title>
          <path
            d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
          ></path>
        </svg>
        Create Room
      </a>
    </div>
    {% for i in rooms %}
      <div class="roomListRoom">
        <div class="roomListRoom__header">
          <a href="{% url 'profile' i.host.id %}" class="roomListRoom__author">
            <div class="avatar avatar--small">
              <img src="https://randomuser.me/api/portraits/women/11.jpg" />
            </div>
            <span>@{{ i.host.username }}</span>
          </a>
          <div class="roomListRoom__actions">
            <span>{{ i.created|timesince }} ago</span>
          </div>
        </div>
        <div class="roomListRoom__content">
          <a href="{% url 'rooms' i.id %}">{{ i.name }}</a>
          <p>
            {{ i.description }}
          </p>
        </div>
        <div class="roomListRoom__meta">
          <a href="{% url 'rooms' i.id %}" class="roomListRoom__joined">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>user-group</title>
              <path
                d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
              ></path>
              <path
                d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
              ></path>
              <path
                d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
              ></path>
              <path
                d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
              ></path>
            </svg>
            {{ i.message_set.all.count }} Commented
          </a>
          <p class="roomListRoom__topic">{{ i.topic }}</p>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

templates/settings.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main class="create-room layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="index.html">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
              ></path>
            </svg>
          </a>
          <h3>Settings</h3>
        </div>
      </div>

      <div class="settings layout__body">
        <div class="settings__avatar">
          <div class="avatar avatar--large active">
            <img src="assets/avatar.svg" id="preview-avatar" />
          </div>
        </div>
        <form class="form" action="#">
          <div class="form__group form__avatar">
            <label for="avatar">Upload Avatar</label>
            <input
              class="form__hide"
              required
              type="file"
              name="avatar"
              id="avatar"
              accept="image/png, image/gif, image/jpeg"
            />
          </div>
          <div class="form__group">
            <label for="name">Full Name</label>
            <input
              id="fullname"
              name="fullname"
              type="text"
              placeholder="e.g. Dennis Ivy"
              value="Dennis Ivy"
            />
          </div>
          <div class="form__group">
            <label for="username">Username</label>
            <input
              id="username"
              name="username"
              type="text"
              placeholder="e.g. @dennis_ivy"
              value="@dennis_ivy"
            />
          </div>
          <div class="form__group">
            <label for="email">Email</label>
            <input id="email" name="email" type="email" placeholder="e.g. user@domain.com" />
          </div>
          <div class="form__group">
            <label for="about">About</label>
            <textarea name="about" id="about" placeholder="Write about yourself..."></textarea>
          </div>
          <div class="form__action">
            <a class="btn btn--dark" href="profile.html">Cancel</a>
            <button class="btn btn--main" type="submit">Update Settings</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock %}

templates/user_profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main class="profile-page layout layout--3">
  <div class="container">
    <!-- Topics Start -->
    {% include 'topics.html' %}
    <!-- Topics End -->

    <!-- Room List Start -->
    <div class="roomList">
      <div class="profile">
        <div class="profile__avatar">
          <div class="avatar avatar--large active">
            <img src="https://randomuser.me/api/portraits/men/11.jpg" />
          </div>
        </div>
        <div class="profile__info">
          <h3>{{ user }}</h3>
          <p>@{{ user.username }}</p>
          <a href="edit-user.html" class="btn btn--main btn--pill">Edit Profile</a>
        </div>
        <div class="profile__about">
          <h3>About</h3>
          <p>
            {{ user.about }}
          </p>
        </div>
      </div>

      <div class="roomList__header">
        <div>
          <h2>Study Rooms Hosted by {{ user.username }}</a>
          </h2>
        </div>
      </div>
      {% for i in rooms %}
      <div class="roomListRoom">
        <div class="roomListRoom__header">
          <a href="{% url 'profile' user.id %}" class="roomListRoom__author">
            <div class="avatar avatar--small active">
              <img src="https://randomuser.me/api/portraits/men/11.jpg" />
            </div>
            <span>@{{ user.username }}</span>
          </a>
          <div class="roomListRoom__actions">
            <span>{{ i.created|timesince }} ago</span>

          </div>
        </div>
        <div class="roomListRoom__content">
          <a href="{% url 'rooms' i.id %}">{{ i.name }}</a>
          <p>
            {{ i.description }}
          </p>
        </div>
        <div class="roomListRoom__meta">
          <a class="roomListRoom__joined">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>user-group</title>
              <path
                d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z">
              </path>
              <path
                d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z">
              </path>
              <path
                d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z">
              </path>
              <path
                d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z">
              </path>
            </svg>
            {{ i.message_set.count }} commented
          </a>
          <p class="roomListRoom__topic">Python</p>
        </div>
      </div>
      {% endfor %}
    </div>
    <!-- Room List End -->

    <!-- Activities Start -->
    {% include 'activity.html' %}
    <!-- Activities End -->
  </div>
</main>
{% endblock %}